### ISSUE TITLE
Socket Error while starting the exporter

### ISSUE THREAD

**Issue by muralikanagala** [picadoh/jload#1]
Hi,

I am trying to setup JMX exporter to collect metrics from a weblogic cluster.
When i run the jload i am seeing the below error.

`./jload 28459 jmx_prometheus_javaagent-0.11.1-SNAPSHOT.jar
2019/02/26 19:08:47 Creating file: /proc/28459/cwd/.attach_pid28459
2019/02/26 19:08:48 Waiting for socket at '/tmp/.java_pid28459' to become available`

Please help me with this.

**Comment by etlfg** [comment]
Exact same error here with docker :
```
$ wget -O jmx_prometheus_javaagent.jar https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.11.0/jmx_prometheus_javaagent-0.11.0.jar
$ docker run --rm picadoh/jload 26797 jmx_prometheus_javaagent.jar                                                                                                  
2019/03/05 10:55:03 Creating file: /tmp/.attach_pid26797
2019/03/05 10:55:04 Waiting for socket at '/tmp/.java_pid26797' to become available
```

**Comment by picadoh** [comment]
Hi @muralikanagala,

Apologies for the late reply.

That is not an error but rather info stating that the loader is waiting for the PID to be reachable. A typical `jload` log would look like:

```
2019/03/18 16:58:53 Creating file: /var/folders/wz/2p4md_rj4fb70mj2cfr9180w0000gp/T//.attach_pid89604
2019/03/18 16:58:54 Waiting for socket at '/var/folders/wz/2p4md_rj4fb70mj2cfr9180w0000gp/T//.java_pid89604' to become available
2019/03/18 16:58:54 Connected
2019/03/18 16:58:54 Sent 1 load instrument false jmx_prometheus_javaagent.jar to socket at /var/folders/wz/2p4md_rj4fb70mj2cfr9180w0000gp/T//.java_pid89604
```

If the `Connected` message does not appear, it means that `jload` can't see the PID and thus can't open a dynamic socket into it.

The same applies to @etlfg scenario, though with a small difference. Docker provides isolation of PID namespaces. Unless you run `jload` in the same [PID namespace](http://man7.org/linux/man-pages/man7/pid_namespaces.7.html) of the target process, it would not be possible to attach an agent into it.

**Comment by muralikanagala** [comment]
Thank you @picadoh !
